apiVersion: v1
kind: Service
metadata:
  labels:
    name: pgadmin
  name: pgadmin
spec:
  ports:
    - name: "1234"
      port: 1234
      targetPort: 80
  selector:
    app: pgadmin
status:
  loadBalancer: {}