apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: node-tp
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: pierrelbg/node-tp:1.0
          resources: {}
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: api
                  key: PORT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: api
                  key: DB_HOST
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: api
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: api
                  key: DB_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: api
                  key: DB_DATABASE
            - name: DB_DAILECT
              valueFrom:
                configMapKeyRef:
                  name: api
                  key: DB_DAILECT
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: api
                  key: DB_PORT
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                configMapKeyRef:
                  name: api
                  key: ACCESS_TOKEN_SECRET
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                configMapKeyRef:
                  name: api
                  key: REFRESH_TOKEN_SECRET
            - name: ACCESS_TOKEN_EXPIRY
              valueFrom:
                configMapKeyRef:
                  name: api
                  key: ACCESS_TOKEN_EXPIRY
            - name: REFRESH_TOKEN_EXPIRY
              valueFrom:
                configMapKeyRef:
                  name: api
                  key: REFRESH_TOKEN_EXPIRY
            - name: REFRESH_TOKEN_COOKIE_NAME
              valueFrom:
                configMapKeyRef:
                  name: api
                  key: REFRESH_TOKEN_COOKIE_NAME

          ports:
            - containerPort: 3000