apiVersion: v1
kind: Secret
metadata:
  name: api
  namespace: node-tp
type: Opaque
data:
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=
  ACCESS_TOKEN_SECRET: WU9VUl9TRUNSRVRfS0VZ
  REFRESH_TOKEN_SECRET: WU9VUl9TRUNSRVRfS0VZ
