apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: node-tp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15.2
        resources: {}
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-claim
      volumes:
        - name: postgres-claim
          hostPath:
            path: /home/pierre/data_postgres
            type: DirectoryOrCreate